name: 'Delete untagged ghcr'
author: 'Chuzkiyahu Raful'
description: 'Delete containers on github container registry without tags'
branding:
  icon: 'trash-2'
  color: 'blue'
inputs:  
  token:
    description: >
      Personal access token (PAT) used to fetch the repository. The PAT is configured
      with the local git config, which enables your scripts to run authenticated git
      commands. The post-job step removes the PAT.
      needs delete:packages permissions
    required: true
 
  repository_owner:
    description: 'The repository owner name'
    default: ${{ github.repository_owner }}
    required: true

  repository:
    description: 'Delete only from repository name'
    required: false

  package_name:
    description: 'Delete only from package name'
    required: false

  untagged_only:
      description: 'Delete only package versions without tag'
      default: true

  except_untagged_multiplatform:
    description: 'Except untagged multiplatform packages from deletion (only for --untagged_only)'
    default: true
  
  owner_type:
      description : "Owner type (org or user)"
      required: true



runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    - run: | 
         python ${{ github.action_path }}/clean_ghcr.py \
        --token ${{ inputs.token }} \
        --repository_owner ${{ inputs.repository_owner }} \
        --repository ${{ inputs.repository }} \
        --package_name ${{ inputs.package_name }} \ 
        --untagged_only ${{ inputs.untagged_only }} \
        --except_untagged_multiplatform ${{ inputs.except_untagged_multiplatform }} \
        --owner_type ${{ inputs.owner_type }}
      shell: bash
