name: yapf-action
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linter_name:
    name: runner / yapf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: install and run yapf
      - run: |
          pip install yapf
          yapf  . --verbose --recursive --in-place --parallel
          is_formatted=$(echo $?)
      
      - name: Create Pull Request
        if: $is_formatted != 0
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "${{ github.head_ref }} Format Python code with psf/black push"
          commit-message: ":art: Format Python code with psf/black"
          body: |
            There appear to be some python formatting errors in ${{ github.sha }}. This pull request
            uses the  formatter to fix these issues.
          base: ${{ github.head_ref }} # Creates pull request onto pull request or commit branch
          branch: ${{ github.head_ref }}_actions_yapf
      - name: Fail if need to format
        if: $is_formatted != 0
        run: exit 1
